apiVersion: apps/v1
kind: Deployment
metadata:
  name: face-detection-deployment
spec:
  replicas: 3
  selector:
    matchLabels:
      app: face-detection
  template:
    metadata:
      labels:
        app: face-detection
    spec:
      containers:
      - name: face-detection-container
        image: lucasmatni/face-detection-tensorjs:latest
        ports:
        - containerPort: 80
