apiVersion: v1
kind: Service
metadata:
  name: face-detection-service
  namespace: default
spec:
  selector:
    app: face-detection
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
      nodePort: 32475
  type: NodePort
